
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the Gadgeteer Designer.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Gadgeteer;
using GTM = Gadgeteer.Modules;

namespace HydraBasicKitDemo
{
    public partial class Program : Gadgeteer.Program
    {
        // GTM.Module defintions
		Gadgeteer.Modules.GHIElectronics.LED7R led;
		Gadgeteer.Modules.GHIElectronics.Joystick joystick;
		Gadgeteer.Modules.GHIElectronics.LightSensor lightSensor;

		public static void Main()
        {
			//Important to initialize the Mainboard first
            Mainboard = new GHIElectronics.Gadgeteer.FEZHydra();			

            Program program = new Program();
			program.InitializeModules();
            program.ProgramStarted();
            program.Run(); // Starts Dispatcher
        }

        private void InitializeModules()
        {   
			// Initialize GTM.Modules and event handlers here.		
			led = new GTM.GHIElectronics.LED7R(11);
		
			lightSensor = new GTM.GHIElectronics.LightSensor(13);
		
			joystick = new GTM.GHIElectronics.Joystick(14);

        }
    }
}
